<?xml version="1.0" encoding="UTF-8"?>
<!-- Quarterly Invoice Summary — generated by Stylus. -->
<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:fo="http://www.w3.org/1999/XSL/Format">

  <xsl:output method="xml" indent="yes"/>
  <xsl:param name="reportTitle">Quarterly Invoice Summary</xsl:param>

  <xsl:template match="/">
    <fo:root>
      <fo:layout-master-set>
        <fo:simple-page-master master-name="page"
                               page-width="210mm"
                               page-height="297mm"
                               margin-top="15mm"
                               margin-bottom="15mm"
                               margin-left="20mm"
                               margin-right="20mm">
          <fo:region-body margin-top="10mm" margin-bottom="10mm"/>
          <fo:region-before extent="8mm"/>
          <fo:region-after extent="8mm"/>
        </fo:simple-page-master>
      </fo:layout-master-set>
      <fo:page-sequence master-reference="page">
        <fo:static-content flow-name="xsl-region-before">
          <fo:block font-size="8pt"><xsl:value-of select="/InvoiceData/Company/Name"/></fo:block>
        </fo:static-content>
        <fo:static-content flow-name="xsl-region-after">
          <fo:block font-size="8pt">Confidential — Finance · Page <fo:page-number/></fo:block>
        </fo:static-content>
        <fo:flow flow-name="xsl-region-body">
          <fo:block font-weight="bold" font-size="18pt" text-align="center"><xsl:value-of select="$reportTitle"/></fo:block>
          <xsl:for-each select="/InvoiceData/Customers/Customer">
            <xsl:sort select="Name"/>
            <fo:block font-weight="bold" font-size="13pt" color="#5145E8"><xsl:value-of select="Name"/> · <xsl:value-of select="Region"/></fo:block>
            <xsl:for-each select="Orders/Order">
              <fo:block font-weight="bold"><xsl:if test="count(LineItem) &gt; 2"><xsl:attribute name="font-style">italic</xsl:attribute></xsl:if>Order <xsl:value-of select="OrderID"/> · <xsl:value-of select="OrderDate"/></fo:block>
              <fo:table table-layout="fixed" width="100%">
                <fo:table-column column-width="proportional-column-width(2.4)"/>
                <fo:table-column column-width="proportional-column-width(0.7)"/>
                <fo:table-column column-width="proportional-column-width(1)"/>
                <fo:table-column column-width="proportional-column-width(1)"/>
                <fo:table-header>
                  <fo:table-row font-weight="bold">
                    <fo:table-cell><fo:block>PRODUCT</fo:block></fo:table-cell>
                    <fo:table-cell><fo:block text-align="right">QTY</fo:block></fo:table-cell>
                    <fo:table-cell><fo:block text-align="right">UNIT PRICE</fo:block></fo:table-cell>
                    <fo:table-cell><fo:block text-align="right">AMOUNT</fo:block></fo:table-cell>
                  </fo:table-row>
                </fo:table-header>
                <fo:table-body>
                  <xsl:for-each select="LineItem">
                    <fo:table-row>
                      <fo:table-cell><fo:block><xsl:value-of select="Product"/></fo:block></fo:table-cell>
                      <fo:table-cell><fo:block text-align="right"><xsl:value-of select="Qty"/></fo:block></fo:table-cell>
                      <fo:table-cell><fo:block text-align="right"><xsl:value-of select="format-number(UnitPrice, &#39;#,##0.00&#39;)"/></fo:block></fo:table-cell>
                      <fo:table-cell><fo:block text-align="right"><xsl:if test="Amount &gt; 500"><xsl:attribute name="font-weight">bold</xsl:attribute><xsl:attribute name="color">#B42318</xsl:attribute></xsl:if><xsl:value-of select="format-number(Amount, &#39;#,##0.00&#39;)"/></fo:block></fo:table-cell>
                    </fo:table-row>
                  </xsl:for-each>
                </fo:table-body>
              </fo:table>
              <xsl:choose>
                <xsl:when test="sum(LineItem/Amount) &gt; 1000">
                  <fo:block font-weight="bold" color="#C0392B">★ High-value order</fo:block>
                </xsl:when>
                <xsl:otherwise>
                  <fo:block>Standard order</fo:block>
                </xsl:otherwise>
              </xsl:choose>
            </xsl:for-each>
          </xsl:for-each>
        </fo:flow>
      </fo:page-sequence>
    </fo:root>
  </xsl:template>
</xsl:stylesheet>
