<?xml version="1.0" encoding="UTF-8"?>
<!-- Web report — generated by Stylus. -->
<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

  <xsl:output method="html" indent="yes"/>

  <xsl:template match="/">
    <html>
      <head>
        <title>Web report</title>
      </head>
      <body>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
