<?xml version="1.0" encoding="UTF-8"?>
<!-- Untitled — generated by Stylus. -->
<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:fo="http://www.w3.org/1999/XSL/Format">

  <xsl:output method="xml" indent="yes"/>

  <xsl:template match="/">
    <fo:root>
      <fo:layout-master-set>
        <fo:simple-page-master master-name="page"
                               page-width="210mm"
                               page-height="297mm"
                               margin-top="15mm"
                               margin-bottom="15mm"
                               margin-left="20mm"
                               margin-right="20mm">
          <fo:region-body margin-top="10mm" margin-bottom="10mm"/>
          <fo:region-before extent="8mm"/>
          <fo:region-after extent="8mm"/>
        </fo:simple-page-master>
      </fo:layout-master-set>
      <fo:page-sequence master-reference="page">
        <fo:flow flow-name="xsl-region-body">
          <fo:block/>
        </fo:flow>
      </fo:page-sequence>
    </fo:root>
  </xsl:template>
</xsl:stylesheet>
