<?xml version="1.0" encoding="UTF-8"?>
<!-- M6 features — generated by Stylus. -->
<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:fo="http://www.w3.org/1999/XSL/Format">

  <xsl:import href="common/branding.xsl"/>
  <xsl:output method="xml" indent="yes"/>

  <xsl:template match="/">
    <fo:root>
      <fo:layout-master-set>
        <fo:simple-page-master master-name="page"
                               page-width="210mm"
                               page-height="297mm"
                               margin-top="15mm"
                               margin-bottom="15mm"
                               margin-left="20mm"
                               margin-right="20mm">
          <fo:region-body margin-top="10mm" margin-bottom="10mm"/>
          <fo:region-before extent="8mm"/>
          <fo:region-after extent="8mm"/>
        </fo:simple-page-master>
      </fo:layout-master-set>
      <fo:page-sequence master-reference="page">
        <fo:static-content flow-name="xsl-region-after">
          <fo:block font-size="8pt">Page <fo:page-number/> of <fo:page-number-citation ref-id="stylus-last"/></fo:block>
        </fo:static-content>
        <fo:flow flow-name="xsl-region-body">
          <fo:block><fo:external-graphic src="url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR4nGP4z8DwHwAFAAH/q842iQAAAABJRU5ErkJggg==')" content-width="12mm"/></fo:block>
          <fo:block>Body line</fo:block>
          <fo:block id="stylus-last"/>
        </fo:flow>
      </fo:page-sequence>
    </fo:root>
  </xsl:template>
</xsl:stylesheet>
