<?xml version="1.0" encoding="UTF-8"?>
<!-- Masters — generated by Stylus. -->
<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:fo="http://www.w3.org/1999/XSL/Format">

  <xsl:output method="xml" indent="yes"/>

  <xsl:template match="/">
    <fo:root>
      <fo:layout-master-set>
        <fo:simple-page-master master-name="cover"
                               page-width="210mm"
                               page-height="297mm"
                               margin-top="40mm"
                               margin-bottom="25mm"
                               margin-left="25mm"
                               margin-right="25mm">
          <fo:region-body margin-top="10mm" margin-bottom="10mm"/>
          <fo:region-before extent="8mm"/>
          <fo:region-after extent="8mm"/>
        </fo:simple-page-master>
        <fo:simple-page-master master-name="odd"
                               page-width="210mm"
                               page-height="297mm"
                               margin-top="15mm"
                               margin-bottom="15mm"
                               margin-left="25mm"
                               margin-right="15mm">
          <fo:region-body margin-top="10mm" margin-bottom="10mm"/>
          <fo:region-before extent="8mm"/>
          <fo:region-after extent="8mm"/>
        </fo:simple-page-master>
        <fo:simple-page-master master-name="even"
                               page-width="210mm"
                               page-height="297mm"
                               margin-top="15mm"
                               margin-bottom="15mm"
                               margin-left="15mm"
                               margin-right="25mm">
          <fo:region-body margin-top="10mm" margin-bottom="10mm"/>
          <fo:region-before extent="8mm"/>
          <fo:region-after extent="8mm"/>
        </fo:simple-page-master>
        <fo:page-sequence-master master-name="stylus-pages">
          <fo:repeatable-page-master-alternatives>
            <fo:conditional-page-master-reference master-reference="cover" page-position="first"/>
            <fo:conditional-page-master-reference master-reference="even" odd-or-even="even"/>
            <fo:conditional-page-master-reference master-reference="odd"/>
          </fo:repeatable-page-master-alternatives>
        </fo:page-sequence-master>
      </fo:layout-master-set>
      <fo:page-sequence master-reference="stylus-pages">
        <fo:flow flow-name="xsl-region-body">
          <fo:block>Body</fo:block>
        </fo:flow>
      </fo:page-sequence>
    </fo:root>
  </xsl:template>
</xsl:stylesheet>
