<?xml version="1.0" encoding="UTF-8"?>
<!-- Web report — generated by Stylus. -->
<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

  <xsl:output method="html" indent="yes"/>

  <xsl:template match="/">
    <html>
      <head>
        <title>Web report</title>
      </head>
      <body>
        <div style="font-weight:bold;"><xsl:if test="Name = 'VIP'"><xsl:attribute name="style">font-weight:bold;color:#B42318;</xsl:attribute></xsl:if>Hello <xsl:value-of select="Name"/></div>
        <table border="1">
          <tr>
            <th>COL</th>
          </tr>
          <xsl:for-each select="Rows/Row">
            <tr>
              <td><xsl:value-of select="Value"/></td>
            </tr>
          </xsl:for-each>
        </table>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
