package dev.stylus.codegen;

import dev.stylus.model.Band;
import dev.stylus.model.ConditionalBand;
import dev.stylus.model.FieldToken;
import dev.stylus.model.GroupBand;
import dev.stylus.model.ImageBand;
import dev.stylus.model.MasterSelector;
import dev.stylus.model.InlineNode;
import dev.stylus.model.OpaqueBand;
import dev.stylus.model.OpaqueInline;
import dev.stylus.model.OutputMode;
import dev.stylus.model.PageCountToken;
import dev.stylus.model.PageMaster;
import dev.stylus.model.PageNumberToken;
import dev.stylus.model.PageSetup;
import dev.stylus.model.ReportDocument;
import dev.stylus.model.SortKey;
import dev.stylus.model.StaticBand;
import dev.stylus.model.StyleProps;
import dev.stylus.model.StyleRule;
import dev.stylus.model.TableBand;
import dev.stylus.model.TableColumn;
import dev.stylus.model.TextRun;
import dev.stylus.model.XslTextInline;

import java.util.List;
import java.util.Map;

/**
 * Model → XSLT writer. Output is deterministic, indented and commented — readable without the
 * designer (F-1.38) and golden-file tested (F-11.4). The emitted shapes are exactly what
 * {@link XslReader} recognizes back (round-trip, N7).
 *
 * Strongest round-trip rule first: an *unmodified* document that came from source is saved as
 * that source, byte-identical — regeneration only happens after actual edits.
 */
public final class XslWriter {

    private static final String NL = "\n";

    public String write(ReportDocument doc) {
        if (!doc.isModified() && doc.originalSource() != null) {
            return doc.originalSource();
        }
        if (doc.isFullyOpaque() && doc.originalSource() != null) {
            // Nothing recognized → we have nothing safer than the original text (N7).
            return doc.originalSource();
        }
        StringBuilder out = new StringBuilder(8 * 1024);
        out.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>").append(NL);
        out.append("<!-- ").append(escapeComment(doc.title())).append(" — generated by Stylus. -->").append(NL);
        if (doc.outputMode() == OutputMode.PIXEL_PERFECT) {
            writeFoStylesheet(doc, out);
        } else {
            writeHtmlStylesheet(doc, out);
        }
        return out.toString();
    }

    // ---------- pixel-perfect (XSL-FO) ----------

    private void writeFoStylesheet(ReportDocument doc, StringBuilder out) {
        PageSetup p = doc.pageSetup();
        out.append("<xsl:stylesheet version=\"1.0\"").append(NL)
           .append("                xmlns:xsl=\"http://www.w3.org/1999/XSL/Transform\"").append(NL)
           .append("                xmlns:fo=\"http://www.w3.org/1999/XSL/Format\"");
        if (usesXdoxslt(doc)) {
            // BI Publisher extension functions (doc 05, F-3.1) — BIP engine only (doc 07).
            out.append(NL).append("                xmlns:xdoxslt=\"").append(NS_XDOXSLT).append("\"");
        }
        out.append(">").append(NL)
           .append(NL);
        writeImports(doc, out);
        out.append("  <xsl:output method=\"xml\" indent=\"yes\"/>").append(NL);
        writeParams(doc, out);
        out.append(NL)
           .append("  <xsl:template match=\"").append(escapeAttr(doc.rootMatch())).append("\">").append(NL)
           .append("    <fo:root>").append(NL)
           .append("      <fo:layout-master-set>").append(NL);
        if (doc.pageMasters().isEmpty()) {
            writeSimplePageMaster("page", p, out);
            out.append("      </fo:layout-master-set>").append(NL)
               .append("      <fo:page-sequence master-reference=\"page\">").append(NL);
        } else {
            // Conditional page layout (F-2.26/F-2.27): masters + first-match-wins selectors.
            for (PageMaster master : doc.pageMasters()) {
                writeSimplePageMaster(master.name(), master.geometry(), out);
            }
            out.append("        <fo:page-sequence-master master-name=\"stylus-pages\">").append(NL)
               .append("          <fo:repeatable-page-master-alternatives>").append(NL);
            List<MasterSelector> selectors = doc.masterSelectors().isEmpty()
                    ? List.of(MasterSelector.any(doc.pageMasters().get(0).name()))
                    : doc.masterSelectors();
            for (MasterSelector selector : selectors) {
                out.append("            <fo:conditional-page-master-reference master-reference=\"")
                   .append(escapeAttr(selector.masterName())).append("\"");
                if (selector.pagePosition() != null) {
                    out.append(" page-position=\"").append(escapeAttr(selector.pagePosition())).append("\"");
                }
                if (selector.oddOrEven() != null) {
                    out.append(" odd-or-even=\"").append(escapeAttr(selector.oddOrEven())).append("\"");
                }
                if (selector.blankOrNot() != null) {
                    out.append(" blank-or-not-blank=\"").append(escapeAttr(selector.blankOrNot())).append("\"");
                }
                out.append("/>").append(NL);
            }
            out.append("          </fo:repeatable-page-master-alternatives>").append(NL)
               .append("        </fo:page-sequence-master>").append(NL)
               .append("      </fo:layout-master-set>").append(NL)
               .append("      <fo:page-sequence master-reference=\"stylus-pages\">").append(NL);
        }

        if (!doc.pageHeader().isEmpty()) {
            out.append("        <fo:static-content flow-name=\"xsl-region-before\">").append(NL);
            writeMarginBlock(doc.pageHeader(), out);
            out.append("        </fo:static-content>").append(NL);
        }
        if (!doc.pageFooter().isEmpty()) {
            out.append("        <fo:static-content flow-name=\"xsl-region-after\">").append(NL);
            writeMarginBlock(doc.pageFooter(), out);
            out.append("        </fo:static-content>").append(NL);
        }

        out.append("        <fo:flow flow-name=\"xsl-region-body\">").append(NL);
        if (doc.bands().isEmpty()) {
            out.append("          <fo:block/>").append(NL);
        } else {
            for (Band band : doc.bands()) {
                writeFoBand(band, out, 10);
            }
        }
        if (usesPageCount(doc)) {
            // The citation anchor for page-count tokens: last block of the flow.
            out.append("          <fo:block id=\"stylus-last\"/>").append(NL);
        }
        out.append("        </fo:flow>").append(NL)
           .append("      </fo:page-sequence>").append(NL)
           .append("    </fo:root>").append(NL)
           .append("  </xsl:template>").append(NL)
           .append("</xsl:stylesheet>").append(NL);
    }

    private void writeSimplePageMaster(String name, PageSetup p, StringBuilder out) {
        out.append("        <fo:simple-page-master master-name=\"").append(escapeAttr(name)).append("\"").append(NL)
           .append("                               page-width=\"").append(mm(p.pageWidthMm())).append("\"").append(NL)
           .append("                               page-height=\"").append(mm(p.pageHeightMm())).append("\"").append(NL)
           .append("                               margin-top=\"").append(mm(p.marginTopMm())).append("\"").append(NL)
           .append("                               margin-bottom=\"").append(mm(p.marginBottomMm())).append("\"").append(NL)
           .append("                               margin-left=\"").append(mm(p.marginLeftMm())).append("\"").append(NL)
           .append("                               margin-right=\"").append(mm(p.marginRightMm())).append("\">").append(NL)
           .append("          <fo:region-body margin-top=\"").append(mm(p.bodyTopMm()))
           .append("\" margin-bottom=\"").append(mm(p.bodyBottomMm())).append("\"/>").append(NL)
           .append("          <fo:region-before extent=\"").append(mm(p.beforeExtentMm())).append("\"/>").append(NL)
           .append("          <fo:region-after extent=\"").append(mm(p.afterExtentMm())).append("\"/>").append(NL)
           .append("        </fo:simple-page-master>").append(NL);
    }

    /**
     * Page header/footer content. A single opaque inline holding FO markup is a static-content
     * region the reader preserved wholesale (attrs outside the subset) — re-emitted verbatim;
     * everything else gets the standard 8pt margin block.
     */
    private void writeMarginBlock(List<InlineNode> content, StringBuilder out) {
        if (content.size() == 1 && content.get(0) instanceof OpaqueInline opaque
                && opaque.xml().stripLeading().startsWith("<fo:")) {
            out.append("          ").append(opaque.xml().strip()).append(NL);
        } else {
            out.append("          <fo:block font-size=\"8pt\">").append(inlines(content))
               .append("</fo:block>").append(NL);
        }
    }

    private void writeFoBand(Band band, StringBuilder out, int indent) {
        String pad = " ".repeat(indent);
        switch (band) {
            case StaticBand b -> out.append(pad).append("<fo:block").append(styleAttrs(b.style()))
                    .append(">").append(ruleIfs(b.rules())).append(inlines(b.content()))
                    .append("</fo:block>").append(NL);

            case GroupBand g -> {
                out.append(pad).append("<xsl:for-each select=\"").append(escapeAttr(g.selectXPath()))
                        .append("\">").append(NL);
                for (SortKey sort : g.sortKeys()) {
                    out.append(pad).append("  <xsl:sort select=\"").append(escapeAttr(sort.selectXPath())).append("\"");
                    if (!sort.ascending()) {
                        out.append(" order=\"descending\"");
                    }
                    if (sort.dataType() == dev.stylus.model.DataType.NUMBER) {
                        out.append(" data-type=\"number\"");
                    }
                    out.append("/>").append(NL);
                }
                for (Band child : g.children()) {
                    writeFoBand(child, out, indent + 2);
                }
                out.append(pad).append("</xsl:for-each>").append(NL);
            }

            case TableBand t -> writeFoTable(t, out, indent);

            case ConditionalBand c -> {
                if (c.hasElse()) {
                    out.append(pad).append("<xsl:choose>").append(NL)
                       .append(pad).append("  <xsl:when test=\"").append(escapeAttr(c.testExpr())).append("\">").append(NL);
                    for (Band child : c.then()) {
                        writeFoBand(child, out, indent + 4);
                    }
                    out.append(pad).append("  </xsl:when>").append(NL)
                       .append(pad).append("  <xsl:otherwise>").append(NL);
                    for (Band child : c.otherwise()) {
                        writeFoBand(child, out, indent + 4);
                    }
                    out.append(pad).append("  </xsl:otherwise>").append(NL)
                       .append(pad).append("</xsl:choose>").append(NL);
                } else {
                    out.append(pad).append("<xsl:if test=\"").append(escapeAttr(c.testExpr())).append("\">").append(NL);
                    for (Band child : c.then()) {
                        writeFoBand(child, out, indent + 2);
                    }
                    out.append(pad).append("</xsl:if>").append(NL);
                }
            }

            case ImageBand img -> {
                out.append(pad).append("<fo:block><fo:external-graphic src=\"url('")
                   .append(escapeAttr(img.src())).append("')\"");
                if (img.widthMm() != null) {
                    out.append(" content-width=\"").append(mm(img.widthMm())).append("\"");
                }
                if (img.heightMm() != null) {
                    out.append(" content-height=\"").append(mm(img.heightMm())).append("\"");
                }
                out.append("/></fo:block>").append(NL);
            }

            case OpaqueBand o -> {
                // Preserved hand-written construct — re-emitted exactly as stored (N7).
                out.append(pad).append(o.xml().strip()).append(NL);
            }
        }
    }

    private void writeFoTable(TableBand t, StringBuilder out, int indent) {
        String pad = " ".repeat(indent);
        out.append(pad).append("<fo:table table-layout=\"fixed\" width=\"100%\">").append(NL);
        for (TableColumn col : t.columns()) {
            out.append(pad).append("  <fo:table-column column-width=\"proportional-column-width(")
               .append(weight(col.widthWeight())).append(")\"/>").append(NL);
        }
        out.append(pad).append("  <fo:table-header>").append(NL)
           .append(pad).append("    <fo:table-row font-weight=\"bold\">").append(NL);
        for (TableColumn col : t.columns()) {
            out.append(pad).append("      <fo:table-cell><fo:block").append(alignAttr(col.align()))
               .append(">").append(escapeText(col.header())).append("</fo:block></fo:table-cell>").append(NL);
        }
        out.append(pad).append("    </fo:table-row>").append(NL)
           .append(pad).append("  </fo:table-header>").append(NL)
           .append(pad).append("  <fo:table-body>").append(NL)
           .append(pad).append("    <xsl:for-each select=\"").append(escapeAttr(t.rowXPath())).append("\">").append(NL)
           .append(pad).append("      <fo:table-row>").append(NL);
        for (TableColumn col : t.columns()) {
            out.append(pad).append("        <fo:table-cell><fo:block").append(alignAttr(col.align()))
               .append(">").append(ruleIfs(col.rules())).append(inlines(col.cell()))
               .append("</fo:block></fo:table-cell>").append(NL);
        }
        out.append(pad).append("      </fo:table-row>").append(NL)
           .append(pad).append("    </xsl:for-each>").append(NL)
           .append(pad).append("  </fo:table-body>").append(NL)
           .append(pad).append("</fo:table>").append(NL);
    }

    // ---------- web mode (HTML) ----------

    private void writeHtmlStylesheet(ReportDocument doc, StringBuilder out) {
        out.append("<xsl:stylesheet version=\"1.0\"").append(NL)
           .append("                xmlns:xsl=\"http://www.w3.org/1999/XSL/Transform\"");
        if (usesXdoxslt(doc)) {
            out.append(NL).append("                xmlns:xdoxslt=\"").append(NS_XDOXSLT).append("\"");
        }
        out.append(">").append(NL)
           .append(NL);
        writeImports(doc, out);
        out.append("  <xsl:output method=\"html\" indent=\"yes\"/>").append(NL);
        writeParams(doc, out);
        out.append(NL)
           .append("  <xsl:template match=\"").append(escapeAttr(doc.rootMatch())).append("\">").append(NL)
           .append("    <html>").append(NL)
           .append("      <head>").append(NL)
           .append("        <title>").append(escapeText(doc.title())).append("</title>").append(NL)
           .append("      </head>").append(NL)
           .append("      <body>").append(NL);
        for (Band band : doc.bands()) {
            writeHtmlBand(band, out, 8);
        }
        out.append("      </body>").append(NL)
           .append("    </html>").append(NL)
           .append("  </xsl:template>").append(NL)
           .append("</xsl:stylesheet>").append(NL);
    }

    private void writeHtmlBand(Band band, StringBuilder out, int indent) {
        String pad = " ".repeat(indent);
        switch (band) {
            case StaticBand b -> out.append(pad).append("<div").append(htmlStyleAttr(b.style()))
                    .append(">").append(htmlRuleIfs(b.rules(), b.style()))
                    .append(inlinesHtml(b.content())).append("</div>").append(NL);
            case GroupBand g -> {
                out.append(pad).append("<xsl:for-each select=\"").append(escapeAttr(g.selectXPath())).append("\">").append(NL);
                for (SortKey sort : g.sortKeys()) {
                    out.append(pad).append("  <xsl:sort select=\"").append(escapeAttr(sort.selectXPath())).append("\"/>").append(NL);
                }
                for (Band child : g.children()) {
                    writeHtmlBand(child, out, indent + 2);
                }
                out.append(pad).append("</xsl:for-each>").append(NL);
            }
            case ImageBand img -> {
                out.append(pad).append("<img src=\"").append(escapeAttr(img.src())).append("\"");
                StringBuilder css = new StringBuilder();
                if (img.widthMm() != null) {
                    css.append("width:").append(mm(img.widthMm())).append(";");
                }
                if (img.heightMm() != null) {
                    css.append("height:").append(mm(img.heightMm())).append(";");
                }
                if (css.length() > 0) {
                    out.append(" style=\"").append(css).append("\"");
                }
                out.append("/>").append(NL);
            }
            case TableBand t -> {
                out.append(pad).append("<table border=\"1\">").append(NL)
                   .append(pad).append("  <tr>").append(NL);
                for (TableColumn col : t.columns()) {
                    out.append(pad).append("    <th>").append(escapeText(col.header())).append("</th>").append(NL);
                }
                out.append(pad).append("  </tr>").append(NL)
                   .append(pad).append("  <xsl:for-each select=\"").append(escapeAttr(t.rowXPath())).append("\">").append(NL)
                   .append(pad).append("    <tr>").append(NL);
                for (TableColumn col : t.columns()) {
                    out.append(pad).append("      <td>").append(htmlRuleIfs(col.rules(), null))
                       .append(inlinesHtml(col.cell())).append("</td>").append(NL);
                }
                out.append(pad).append("    </tr>").append(NL)
                   .append(pad).append("  </xsl:for-each>").append(NL)
                   .append(pad).append("</table>").append(NL);
            }
            case ConditionalBand c -> {
                out.append(pad).append("<xsl:if test=\"").append(escapeAttr(c.testExpr())).append("\">").append(NL);
                for (Band child : c.then()) {
                    writeHtmlBand(child, out, indent + 2);
                }
                out.append(pad).append("</xsl:if>").append(NL);
            }
            case OpaqueBand o -> out.append(pad).append(o.xml().strip()).append(NL);
        }
    }

    // ---------- shared pieces ----------

    private static final String NS_XDOXSLT =
            "http://www.oracle.com/XSL/Transform/java/oracle.apps.xdo.template.rtf.XSLTFunctions";

    /** True when any model expression calls a BIP extension function (needs the ns declared). */
    private static boolean usesXdoxslt(ReportDocument doc) {
        return inlinesUse(doc.pageHeader()) || inlinesUse(doc.pageFooter())
                || doc.bands().stream().anyMatch(XslWriter::bandUses);
    }

    private static boolean bandUses(Band band) {
        return switch (band) {
            case StaticBand b -> inlinesUse(b.content()) || rulesUse(b.rules());
            case GroupBand g -> g.selectXPath().contains("xdoxslt:")
                    || g.sortKeys().stream().anyMatch(s -> s.selectXPath().contains("xdoxslt:"))
                    || g.children().stream().anyMatch(XslWriter::bandUses);
            case TableBand t -> t.rowXPath().contains("xdoxslt:")
                    || t.columns().stream().anyMatch(c -> inlinesUse(c.cell()) || rulesUse(c.rules()));
            case ConditionalBand c -> c.testExpr().contains("xdoxslt:")
                    || c.then().stream().anyMatch(XslWriter::bandUses)
                    || c.otherwise().stream().anyMatch(XslWriter::bandUses);
            case ImageBand i -> false;
            case OpaqueBand o -> o.xml().contains("xdoxslt:");
        };
    }

    private static boolean rulesUse(List<StyleRule> rules) {
        return rules.stream().anyMatch(r -> r.testExpr().contains("xdoxslt:"));
    }

    private static boolean inlinesUse(List<InlineNode> nodes) {
        return nodes.stream().anyMatch(n -> switch (n) {
            case FieldToken f -> f.xpath().contains("xdoxslt:");
            case OpaqueInline o -> o.xml().contains("xdoxslt:");
            default -> false;
        });
    }

    private void writeParams(ReportDocument doc, StringBuilder out) {
        for (Map.Entry<String, String> param : doc.parameters().entrySet()) {
            out.append("  <xsl:param name=\"").append(escapeAttr(param.getKey())).append("\">")
               .append(escapeText(param.getValue())).append("</xsl:param>").append(NL);
        }
    }

    /** Subtemplate imports (F-6.2) — xsl:import must be the first stylesheet children. */
    private void writeImports(ReportDocument doc, StringBuilder out) {
        for (String href : doc.imports()) {
            out.append("  <xsl:import href=\"").append(escapeAttr(href)).append("\"/>").append(NL);
        }
    }

    /** True when any inline content anywhere carries a page-count token (needs the anchor). */
    private static boolean usesPageCount(ReportDocument doc) {
        return hasPageCount(doc.pageHeader()) || hasPageCount(doc.pageFooter())
                || doc.bands().stream().anyMatch(XslWriter::bandHasPageCount);
    }

    private static boolean bandHasPageCount(Band band) {
        return switch (band) {
            case StaticBand b -> hasPageCount(b.content());
            case GroupBand g -> g.children().stream().anyMatch(XslWriter::bandHasPageCount);
            case TableBand t -> t.columns().stream().anyMatch(c -> hasPageCount(c.cell()));
            case ConditionalBand c -> c.then().stream().anyMatch(XslWriter::bandHasPageCount)
                    || c.otherwise().stream().anyMatch(XslWriter::bandHasPageCount);
            case ImageBand i -> false;
            case OpaqueBand o -> false;
        };
    }

    private static boolean hasPageCount(List<InlineNode> nodes) {
        return nodes.stream().anyMatch(n -> n instanceof PageCountToken);
    }

    /** Inline content on one line — no stray whitespace inside blocks. */
    private String inlines(List<InlineNode> nodes) {
        StringBuilder sb = new StringBuilder();
        for (InlineNode node : nodes) {
            switch (node) {
                case TextRun t -> sb.append(escapeText(t.text()));
                case FieldToken f -> {
                    if (f.format().dataType() == dev.stylus.model.DataType.NUMBER && f.format().hasMask()) {
                        sb.append("<xsl:value-of select=\"format-number(").append(escapeAttr(f.xpath()))
                          .append(", &#39;").append(escapeAttr(f.format().mask())).append("&#39;)\"/>");
                    } else {
                        sb.append("<xsl:value-of select=\"").append(escapeAttr(f.xpath())).append("\"/>");
                    }
                }
                case PageNumberToken p -> sb.append("<fo:page-number/>");
                case PageCountToken p ->
                        sb.append("<fo:page-number-citation ref-id=\"stylus-last\"/>");
                case XslTextInline x -> sb.append("<xsl:text>").append(ncrEscape(x.text()))
                        .append("</xsl:text>");
                case OpaqueInline o -> sb.append(o.xml());
            }
        }
        return sb.toString();
    }

    private String inlinesHtml(List<InlineNode> nodes) {
        StringBuilder sb = new StringBuilder();
        for (InlineNode node : nodes) {
            switch (node) {
                case TextRun t -> sb.append(escapeText(t.text()));
                case FieldToken f -> sb.append("<xsl:value-of select=\"")
                        .append(escapeAttr(f.xpath())).append("\"/>");
                case PageNumberToken p -> { /* no page numbers in unlimited-width web output */ }
                case PageCountToken p -> { /* idem */ }
                case XslTextInline x -> sb.append("<xsl:text>").append(ncrEscape(x.text()))
                        .append("</xsl:text>");
                case OpaqueInline o -> sb.append(o.xml());
            }
        }
        return sb.toString();
    }

    /**
     * Escapes text for {@code xsl:text} bodies: XML specials plus **numeric character
     * references** for every invisible or ambiguous character (controls incl. tab/newline —
     * inline content is emitted on one line — no-break/thin/zero-width spaces, soft hyphens,
     * BOM). Visible characters (é, €, —) stay literal. Deterministic, so regeneration is a
     * fixed point; also used by the UI to preview the emitted form.
     */
    public static String ncrEscape(String text) {
        StringBuilder sb = new StringBuilder(text.length() + 8);
        for (int i = 0; i < text.length(); ) {
            int cp = text.codePointAt(i);
            if (cp == '&') {
                sb.append("&amp;");
            } else if (cp == '<') {
                sb.append("&lt;");
            } else if (cp == '>') {
                sb.append("&gt;");
            } else if (isInvisible(cp)) {
                sb.append("&#x").append(Integer.toHexString(cp).toUpperCase()).append(";");
            } else {
                sb.appendCodePoint(cp);
            }
            i += Character.charCount(cp);
        }
        return sb.toString();
    }

    private static boolean isInvisible(int cp) {
        return cp < 0x20                       // controls incl. tab, newline
                || (cp >= 0x7F && cp <= 0xA0)  // DEL + C1 + no-break space
                || cp == 0xAD                  // soft hyphen
                || (cp >= 0x2000 && cp <= 0x200F) // en/em/thin spaces, ZW, marks
                || cp == 0x2028 || cp == 0x2029
                || cp == 0x202F || cp == 0x205F
                || cp == 0x2060 || cp == 0xFEFF;
    }

    /**
     * Conditional-format rules (F-1.29) as leading {@code xsl:if} children setting FO attributes.
     * Emitted before inline content ({@code xsl:attribute} must precede other result content);
     * one line, no whitespace — the reader recognizes exactly this shape back into StyleRules.
     */
    private static String ruleIfs(List<StyleRule> rules) {
        StringBuilder sb = new StringBuilder();
        for (StyleRule rule : rules) {
            if (rule.testExpr().isBlank() || rule.style().isEmpty()) {
                continue;
            }
            sb.append("<xsl:if test=\"").append(escapeAttr(rule.testExpr())).append("\">");
            StyleProps s = rule.style();
            if (Boolean.TRUE.equals(s.bold())) {
                ruleAttr(sb, "font-weight", "bold");
            }
            if (Boolean.TRUE.equals(s.italic())) {
                ruleAttr(sb, "font-style", "italic");
            }
            if (s.fontSizePt() != null) {
                ruleAttr(sb, "font-size", s.fontSizePt() + "pt");
            }
            if (s.color() != null) {
                ruleAttr(sb, "color", s.color());
            }
            if (s.textAlign() != null) {
                ruleAttr(sb, "text-align", s.textAlign());
            }
            if (s.fontFamily() != null) {
                ruleAttr(sb, "font-family", s.fontFamily());
            }
            if (s.background() != null) {
                ruleAttr(sb, "background-color", s.background());
            }
            String decoration = textDecoration(s);
            if (decoration != null) {
                ruleAttr(sb, "text-decoration", decoration);
            }
            if (s.lineHeight() != null) {
                ruleAttr(sb, "line-height", s.lineHeight());
            }
            sb.append("</xsl:if>");
        }
        return sb.toString();
    }

    private static void ruleAttr(StringBuilder sb, String name, String value) {
        sb.append("<xsl:attribute name=\"").append(name).append("\">")
          .append(escapeText(value)).append("</xsl:attribute>");
    }

    /**
     * HTML-mode rules: each rule replaces the whole {@code style} attribute with base CSS plus
     * the rule's overrides (attribute re-addition replaces, so the base must be carried along).
     */
    private static String htmlRuleIfs(List<StyleRule> rules, StyleProps base) {
        StringBuilder sb = new StringBuilder();
        for (StyleRule rule : rules) {
            if (rule.testExpr().isBlank() || rule.style().isEmpty()) {
                continue;
            }
            sb.append("<xsl:if test=\"").append(escapeAttr(rule.testExpr())).append("\">")
              .append("<xsl:attribute name=\"style\">")
              .append(escapeText(css(base) + css(rule.style())))
              .append("</xsl:attribute></xsl:if>");
        }
        return sb.toString();
    }

    private static String styleAttrs(StyleProps style) {
        if (style == null || style.isEmpty()) {
            return "";
        }
        StringBuilder sb = new StringBuilder();
        if (Boolean.TRUE.equals(style.bold())) {
            sb.append(" font-weight=\"bold\"");
        }
        if (Boolean.TRUE.equals(style.italic())) {
            sb.append(" font-style=\"italic\"");
        }
        if (style.fontSizePt() != null) {
            sb.append(" font-size=\"").append(escapeAttr(style.fontSizePt())).append("pt\"");
        }
        if (style.color() != null) {
            sb.append(" color=\"").append(escapeAttr(style.color())).append("\"");
        }
        if (style.textAlign() != null) {
            sb.append(" text-align=\"").append(escapeAttr(style.textAlign())).append("\"");
        }
        // Typography extension — appended after the M4 subset so old output stays byte-stable.
        if (style.fontFamily() != null) {
            sb.append(" font-family=\"").append(escapeAttr(style.fontFamily())).append("\"");
        }
        if (style.background() != null) {
            sb.append(" background-color=\"").append(escapeAttr(style.background())).append("\"");
        }
        String decoration = textDecoration(style);
        if (decoration != null) {
            sb.append(" text-decoration=\"").append(decoration).append("\"");
        }
        if (style.lineHeight() != null) {
            sb.append(" line-height=\"").append(escapeAttr(style.lineHeight())).append("\"");
        }
        return sb.toString();
    }

    /** Combined text-decoration value, or null when neither flag is set. */
    private static String textDecoration(StyleProps style) {
        boolean underline = Boolean.TRUE.equals(style.underline());
        boolean strike = Boolean.TRUE.equals(style.strike());
        if (underline && strike) {
            return "underline line-through";
        }
        if (underline) {
            return "underline";
        }
        if (strike) {
            return "line-through";
        }
        return null;
    }

    private static String htmlStyleAttr(StyleProps style) {
        if (style == null || style.isEmpty()) {
            return "";
        }
        return " style=\"" + escapeAttr(css(style)) + "\"";
    }

    private static String css(StyleProps style) {
        if (style == null || style.isEmpty()) {
            return "";
        }
        StringBuilder css = new StringBuilder();
        if (Boolean.TRUE.equals(style.bold())) {
            css.append("font-weight:bold;");
        }
        if (Boolean.TRUE.equals(style.italic())) {
            css.append("font-style:italic;");
        }
        if (style.fontSizePt() != null) {
            css.append("font-size:").append(style.fontSizePt()).append("pt;");
        }
        if (style.color() != null) {
            css.append("color:").append(style.color()).append(";");
        }
        if (style.textAlign() != null) {
            css.append("text-align:").append(style.textAlign()).append(";");
        }
        if (style.fontFamily() != null) {
            css.append("font-family:").append(style.fontFamily()).append(";");
        }
        if (style.background() != null) {
            css.append("background-color:").append(style.background()).append(";");
        }
        String decoration = textDecoration(style);
        if (decoration != null) {
            css.append("text-decoration:").append(decoration).append(";");
        }
        if (style.lineHeight() != null) {
            css.append("line-height:").append(style.lineHeight()).append(";");
        }
        return css.toString();
    }

    private static String alignAttr(String align) {
        return align == null ? "" : " text-align=\"" + escapeAttr(align) + "\"";
    }

    private static String weight(double w) {
        return w == Math.rint(w) ? Long.toString((long) w) : Double.toString(w);
    }

    /** Millimetre length with trailing zeros trimmed: 210 → "210mm", 215.9 → "215.9mm". */
    private static String mm(double value) {
        String s = value == Math.rint(value)
                ? Long.toString((long) value)
                : Double.toString(value);
        return s + "mm";
    }

    private static String escapeText(String s) {
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    }

    private static String escapeAttr(String s) {
        return escapeText(s).replace("\"", "&quot;");
    }

    private static String escapeComment(String s) {
        return s.replace("--", "‐‐");
    }
}
